### PR TITLE
administration page

### LINKED ISSUE #21: Administration page (Administrator list page)
Frontend implementation based on components in page and provided information architecture
Breadcrumbs, LinkBlocks, headings, overviews.

No category/list toggle yet.

### PR DESCRIPTION
**Pull request by schalkneethling**
Add administration index page

This also adds Prettier and eslint

fix #21

### CODE REVIEW

**Comment by schalkneethling** [comment]
Screenshot 2020-10-22 at 20 36 17

**Comment by jbothma** [comment]
This data is supposed to be breadcrumbs

Screenshot_2020-10-22_20-38-24

**Comment by jbothma** [comment]
Let's clean up that placeholder Walter Linnert before showing the LinkBlocks

Screenshot_2020-10-22_20-40-10

**Comment by jbothma** [comment]
- No nead for section headings - we just need a fullwidthgrid and a linkblock
- We want the linkblock with the photo placeholder and arrow on the right.

Screenshot_2020-10-22_20-44-48

**Comment by schalkneethling** [comment]
Screenshot 2020-10-22 at 21 31 23

@jbothma updated

**Comment by schalkneethling** [comment]
> * No nead for section headings - we just need a fullwidthgrid and a linkblock

Whoops, missed that.

> We want the linkblock with the photo placeholder and arrow on the right.

Gotcha

**Comment by schalkneethling** [comment]
> > * No nead for section headings - we just need a fullwidthgrid and a linkblock
> 
> Whoops, missed that.

Done.

**Comment by schalkneethling** [comment]
> * arrow on the right

Currently I am using `LinkBlock` and passing `icon_classes` to `subjectIconClasses` but, for the current two entries, they are both `null`

**Pull request merged**
