### PR TITLE
tab links are anchors

### LINKED ISSUE #34: Tab links are anchor tags
- import webflow export
- Replace hacks with simple component clone

### PR DESCRIPTION
**Pull request by schalkneethling**
- Imports the latest Webflow export
- Refactors `tabs` into a component with a `static` method to set the active tab.

Currently, there is also this call to clean out the tab container element. We may want to avoid this by not having any default tab elements inside the tab container in `main`

```
this.$tabsContainer.empty();
```

fix #34

### CODE REVIEW

**Comment by schalkneethling** [comment]
@jbothma This is ready for review again. I have not addressed https://github.com/OpenUpSA/muni-portal-frontend/issues/37 as I have some questions around those classes. Currently, there does not seem to be any clear distinction between a lot of these link blocks. We probably also have more link blocks than we need.

**Comment by jbothma** [comment]
fails to find subtitle container on elec service page

Screenshot_2020-11-03_15-01-11

**Comment by jbothma** [comment]
Screenshot_2020-11-03_15-02-09

subtitle demo text shown on service index page

**Comment by jbothma** [comment]
I think the tab link root tag should be `.tab-links__wrap` and not `a.tab-link`

Screenshot_2020-11-03_15-04-59
Screenshot_2020-11-03_15-06-33

**Comment by schalkneethling** [comment]
> I think the tab link root tag should be `.tab-links__wrap` and not `a.tab-link`

I do not think so. Remember it was changed to be anchor links. In the `styles` container `div` there is only the `a.tab-link` elements:

Screenshot 2020-11-03 at 15 21 51

**Comment by schalkneethling** [comment]
> subtitle demo text shown on service index page

Yes, that is part of what I want to address with #37 but, I think we need to take a step back and look at what we currently have and find a way to make selecting the appropriate template simpler. That is why I left it like this for right now.

**Comment by schalkneethling** [comment]
> fails to find subtitle container on elec service page

Aha! I see why this fails now. So, for "Postal address" and "Fax", the `targetIconClasses` property is an empty string and this evaluates to `false` so, for these a different template is returned that does not contain a `subtitle`.

So, we need to update the conditional a bit:

```
if (
      (props.targetIconClasses || props.targetIconClasses === "") &&
      props.shadedTarget &&
      props.subtitle
    ) {
```

Screenshot 2020-11-04 at 09 07 10

**Comment by schalkneethling** [comment]
> subtitle demo text shown on service index page

Resolved.

Screenshot 2020-11-04 at 09 11 50

**Comment by jbothma** [comment]
these ones shouldn't have a target icon :)

You could use this one instead for these sort of contacts? https://trello.com/c/6lAijO3o/131-show-office-hours#comment-5f992a9bc2a17f8dab0ed2e5

**Comment by schalkneethling** [comment]
@jbothma ready for review.

Screenshot 2020-11-04 at 14 29 11

**Pull request merged**
